{
 "title": "Home",
 "tags": [ "home" ],
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "USD Balance",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "$" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  start_time AS \"time\",\n  usd\nFROM balances\nWHERE\n  $__timeFilter(start_time)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "BTC Balance",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "₿" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  start_time AS \"time\",\n  usd / btc_usd_price AS btc\nFROM\n  balances\nWHERE\n  $__timeFilter(start_time)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "BTC/USD Price",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "$" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  start_time AS \"time\",\n  btc_usd_price\nFROM balances\nWHERE\n  $__timeFilter(start_time)\nORDER BY 1"
    }
   ]
  }
 ]
}