{
 "title": "Large Cap Funding Rates",
 "tags": [ "large-cap-funding-rates" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "venue",
    "query": "SELECT venue FROM funding_rates ORDER BY venue"
   },
   {
    "name": "base",
    "query": "SELECT base FROM products GROUP BY base ORDER BY base"
   },
   {
    "name": "quote",
    "query": "SELECT quote FROM products GROUP BY quote ORDER BY quote"
   }
  ]
 },
 "panels": [
  {
   "title": "Annualized",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  funding_rates.time,\n  funding_rates.venue || ':' || funding_rates.product AS text,\n  funding_rates.rate * 24 * 365 * 100 AS rate\nFROM funding_rates\n   JOIN products ON products.symbol = funding_rates.product\nWHERE\n  funding_rates.venue IN ($venue)\n  AND products.base IN ($base)\n  AND products.quote IN ($quote)\nORDER BY funding_rates.time"
    }
   ]
  },
  {
   "title": "BTC/USD 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND product = 'btc-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "BTC/USD 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND product = 'btc-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "BTC/USD 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND product = 'btc-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "BTC/USD 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND product = 'btc-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "BTC/USD 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND product = 'btc-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "ETH/USD 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND product = 'eth-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "ETH/USD 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND product = 'eth-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "ETH/USD 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND product = 'eth-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "ETH/USD 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND product = 'eth-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "ETH/USD 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND product = 'eth-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "BNB/USD 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND product = 'bnb-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "BNB/USD 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND product = 'bnb-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "BNB/USD 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND product = 'bnb-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "BNB/USD 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND product = 'bnb-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "BNB/USD 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND product = 'bnb-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "XRP/USD 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND product = 'xrp-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "XRP/USD 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND product = 'xrp-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "XRP/USD 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND product = 'xrp-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "XRP/USD 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND product = 'xrp-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "XRP/USD 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND product = 'xrp-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "UNI/USD 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND product = 'uni-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "UNI/USD 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND product = 'uni-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "UNI/USD 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND product = 'uni-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "UNI/USD 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND product = 'uni-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "UNI/USD 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND product = 'uni-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "LTC/USD 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND product = 'ltc-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "LTC/USD 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND product = 'ltc-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "LTC/USD 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND product = 'ltc-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "LTC/USD 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND product = 'ltc-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "LTC/USD 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND product = 'ltc-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "DOGE/USD 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND product = 'doge-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "DOGE/USD 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND product = 'doge-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "DOGE/USD 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND product = 'doge-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "DOGE/USD 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND product = 'doge-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "DOGE/USD 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND product = 'doge-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "LINK/USD 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND product = 'link-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "LINK/USD 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND product = 'link-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "LINK/USD 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND product = 'link-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "LINK/USD 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND product = 'link-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "LINK/USD 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND product = 'link-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "BCH/USD 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND product = 'bch-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "BCH/USD 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND product = 'bch-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "BCH/USD 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND product = 'bch-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "BCH/USD 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND product = 'bch-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "BCH/USD 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND product = 'bch-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "TRX/USD 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND product = 'trx-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "TRX/USD 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND product = 'trx-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "TRX/USD 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND product = 'trx-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "TRX/USD 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND product = 'trx-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "TRX/USD 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND product = 'trx-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "SOL/USD 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND product = 'sol-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "SOL/USD 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND product = 'sol-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "SOL/USD 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND product = 'sol-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "SOL/USD 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND product = 'sol-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "SOL/USD 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND product = 'sol-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "CRO/USD 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND product = 'cro-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "CRO/USD 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND product = 'cro-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "CRO/USD 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND product = 'cro-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "CRO/USD 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND product = 'cro-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "CRO/USD 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND product = 'cro-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "AAVE/USD 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND product = 'aave-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "AAVE/USD 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND product = 'aave-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "AAVE/USD 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND product = 'aave-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "AAVE/USD 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND product = 'aave-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "AAVE/USD 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND product = 'aave-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "FTT/USD 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND product = 'ftt-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "FTT/USD 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND product = 'ftt-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "FTT/USD 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND product = 'ftt-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "FTT/USD 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND product = 'ftt-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "FTT/USD 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND product = 'ftt-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "MKR/USD 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND product = 'mkr-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "MKR/USD 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND product = 'mkr-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "MKR/USD 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND product = 'mkr-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "MKR/USD 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND product = 'mkr-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "MKR/USD 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND product = 'mkr-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "CHZ/USD 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND product = 'chz-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "CHZ/USD 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND product = 'chz-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "CHZ/USD 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND product = 'chz-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "CHZ/USD 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND product = 'chz-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "CHZ/USD 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND product = 'chz-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "COMP/USD 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND product = 'comp-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "COMP/USD 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND product = 'comp-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "COMP/USD 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND product = 'comp-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "COMP/USD 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND product = 'comp-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "COMP/USD 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND product = 'comp-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "ENJ/USD 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND product = 'enj-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "ENJ/USD 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND product = 'enj-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "ENJ/USD 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND product = 'enj-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "ENJ/USD 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND product = 'enj-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "ENJ/USD 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND product = 'enj-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "SNX/USD 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND product = 'snx-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "SNX/USD 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND product = 'snx-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "SNX/USD 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND product = 'snx-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "SNX/USD 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND product = 'snx-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "SNX/USD 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND product = 'snx-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "SUSHI/USD 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND product = 'sushi-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "SUSHI/USD 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND product = 'sushi-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "SUSHI/USD 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND product = 'sushi-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "SUSHI/USD 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND product = 'sushi-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "SUSHI/USD 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND product = 'sushi-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "MATIC/USD 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND product = 'matic-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "MATIC/USD 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND product = 'matic-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "MATIC/USD 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND product = 'matic-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "MATIC/USD 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND product = 'matic-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "MATIC/USD 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND product = 'matic-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "YFI/USD 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND product = 'yfi-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "YFI/USD 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND product = 'yfi-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "YFI/USD 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND product = 'yfi-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "YFI/USD 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND product = 'yfi-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "YFI/USD 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND product = 'yfi-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "WAVES/USD 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND product = 'waves-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "WAVES/USD 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND product = 'waves-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "WAVES/USD 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND product = 'waves-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "WAVES/USD 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND product = 'waves-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "CRO/USD 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND product = 'cro-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "BNT/USD 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND product = 'bnt-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "BNT/USD 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND product = 'bnt-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "BNT/USD 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND product = 'bnt-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "BNT/USD 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND product = 'bnt-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "BNT/USD 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND product = 'bnt-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "OMG/USD 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND product = 'omg-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "OMG/USD 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND product = 'omg-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "OMG/USD 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND product = 'omg-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "OMG/USD 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND product = 'omg-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "OMG/USD 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND product = 'omg-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "OKB/USD 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND product = 'okb-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "OKB/USD 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND product = 'okb-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "OKB/USD 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND product = 'okb-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "OKB/USD 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND product = 'okb-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "OKB/USD 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND product = 'okb-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "DENT/USD 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND product = 'dent-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "DENT/USD 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND product = 'dent-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "DENT/USD 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND product = 'dent-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "DENT/USD 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND product = 'dent-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "DENT/USD 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND product = 'dent-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "FTM/USD 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND product = 'ftm-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "FTM/USD 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND product = 'ftm-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "FTM/USD 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND product = 'ftm-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "FTM/USD 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND product = 'ftm-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "FTM/USD 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND product = 'ftm-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "BTMX/USD 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND product = 'btmx-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "BTMX/USD 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND product = 'btmx-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "BTMX/USD 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND product = 'btmx-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "BTMX/USD 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND product = 'btmx-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "BTMX/USD 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND product = 'btmx-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "1INCH/USD 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND product = '1inch-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "1INCH/USD 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND product = '1inch-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "1INCH/USD 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND product = '1inch-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "1INCH/USD 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND product = '1inch-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "1INCH/USD 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND product = '1inch-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "CRV/USD 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND product = 'crv-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "CRV/USD 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND product = 'crv-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "CRV/USD 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND product = 'crv-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "CRV/USD 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND product = 'crv-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "CRV/USD 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND product = 'crv-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "LRC/USD 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND product = 'lrc-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "LRC/USD 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND product = 'lrc-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "LRC/USD 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND product = 'lrc-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "LRC/USD 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND product = 'lrc-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "LRC/USD 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND product = 'lrc-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "KNC/USD 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND product = 'knc-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "KNC/USD 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND product = 'knc-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "KNC/USD 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND product = 'knc-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "KNC/USD 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND product = 'knc-perp'\nGROUP BY venue, product"
    }
   ]
  },
  {
   "title": "KNC/USD 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || product AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM funding_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND product = 'knc-perp'\nGROUP BY venue, product"
    }
   ]
  }
 ]
}