{
 "title": "Spot Lending Rates",
 "tags": [
  "spot-lending-rates",
  "rates"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "venue",
    "query": "SELECT venue FROM lending_rates GROUP BY venue ORDER BY venue"
   },
   {
    "name": "token",
    "query": "SELECT tokens.symbol FROM tokens JOIN products ON products.base = tokens.symbol OR products.quote = tokens.symbol GROUP BY tokens.symbol ORDER BY tokens.symbol ASC"
   }
  ]
 },
 "panels": [
  {
   "title": "Annualized",
   "type": "graph",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  lending_rates.time,\n  lending_rates.venue || ':' || lending_rates.token AS text,\n  lending_rates.rate * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  lending_rates.venue IN ($venue)\n  AND lending_rates.token IN ($token)\nORDER BY lending_rates.time"
    }
   ]
  },
  {
   "title": "USD 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND token = 'usd'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "USD 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND token = 'usd'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "USD 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND token = 'usd'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "USD 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND token = 'usd'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "USD 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND token = 'usd'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "USDT 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND token = 'usdt'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "USDT 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND token = 'usdt'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "USDT 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND token = 'usdt'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "USDT 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND token = 'usdt'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "USDT 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND token = 'usdt'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "BTC 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND token = 'btc'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "BTC 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND token = 'btc'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "BTC 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND token = 'btc'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "BTC 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND token = 'btc'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "BTC 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND token = 'btc'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "ETH 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND token = 'eth'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "ETH 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND token = 'eth'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "ETH 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND token = 'eth'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "ETH 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND token = 'eth'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "ETH 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND token = 'eth'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "BNB 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND token = 'bnb'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "BNB 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND token = 'bnb'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "BNB 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND token = 'bnb'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "BNB 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND token = 'bnb'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "BNB 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND token = 'bnb'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "XRP 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND token = 'xrp'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "XRP 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND token = 'xrp'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "XRP 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND token = 'xrp'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "XRP 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND token = 'xrp'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "XRP 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND token = 'xrp'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "UNI 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND token = 'uni'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "UNI 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND token = 'uni'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "UNI 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND token = 'uni'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "UNI 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND token = 'uni'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "UNI 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND token = 'uni'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "LTC 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND token = 'ltc'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "LTC 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND token = 'ltc'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "LTC 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND token = 'ltc'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "LTC 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND token = 'ltc'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "LTC 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND token = 'ltc'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "DOGE 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND token = 'doge'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "DOGE 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND token = 'doge'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "DOGE 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND token = 'doge'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "DOGE 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND token = 'doge'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "DOGE 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND token = 'doge'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "LINK 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND token = 'link'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "LINK 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND token = 'link'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "LINK 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND token = 'link'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "LINK 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND token = 'link'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "LINK 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND token = 'link'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "BCH 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND token = 'bch'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "BCH 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND token = 'bch'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "BCH 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND token = 'bch'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "BCH 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND token = 'bch'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "BCH 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND token = 'bch'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "TRX 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND token = 'trx'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "TRX 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND token = 'trx'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "TRX 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND token = 'trx'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "TRX 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND token = 'trx'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "TRX 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND token = 'trx'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "SOL 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND token = 'sol'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "SOL 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND token = 'sol'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "SOL 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND token = 'sol'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "SOL 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND token = 'sol'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "SOL 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND token = 'sol'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "CRO 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND token = 'cro'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "CRO 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND token = 'cro'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "CRO 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND token = 'cro'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "CRO 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND token = 'cro'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "CRO 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND token = 'cro'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "AAVE 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND token = 'aave'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "AAVE 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND token = 'aave'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "AAVE 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND token = 'aave'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "AAVE 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND token = 'aave'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "AAVE 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND token = 'aave'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "FTT 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND token = 'ftt'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "FTT 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND token = 'ftt'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "FTT 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND token = 'ftt'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "FTT 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND token = 'ftt'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "FTT 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND token = 'ftt'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "MKR 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND token = 'mkr'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "MKR 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND token = 'mkr'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "MKR 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND token = 'mkr'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "MKR 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND token = 'mkr'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "MKR 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND token = 'mkr'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "CHZ 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND token = 'chz'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "CHZ 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND token = 'chz'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "CHZ 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND token = 'chz'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "CHZ 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND token = 'chz'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "CHZ 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND token = 'chz'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "COMP 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND token = 'comp'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "COMP 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND token = 'comp'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "COMP 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND token = 'comp'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "COMP 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND token = 'comp'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "COMP 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND token = 'comp'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "ENJ 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND token = 'enj'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "ENJ 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND token = 'enj'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "ENJ 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND token = 'enj'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "ENJ 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND token = 'enj'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "ENJ 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND token = 'enj'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "SNX 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND token = 'snx'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "SNX 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND token = 'snx'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "SNX 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND token = 'snx'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "SNX 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND token = 'snx'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "SNX 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND token = 'snx'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "SUSHI 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND token = 'sushi'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "SUSHI 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND token = 'sushi'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "SUSHI 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND token = 'sushi'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "SUSHI 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND token = 'sushi'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "SUSHI 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND token = 'sushi'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "MATIC 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND token = 'matic'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "MATIC 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND token = 'matic'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "MATIC 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND token = 'matic'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "MATIC 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND token = 'matic'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "MATIC 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND token = 'matic'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "YFI 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND token = 'yfi'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "YFI 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND token = 'yfi'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "YFI 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND token = 'yfi'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "YFI 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND token = 'yfi'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "YFI 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND token = 'yfi'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "RUNE 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND token = 'rune'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "RUNE 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND token = 'rune'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "RUNE 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND token = 'rune'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "RUNE 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND token = 'rune'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "RUNE 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND token = 'rune'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "LINK 4h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '4 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '4 hours'\n  AND token = 'link'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "LINK 24h APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '24 hours' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '24 hours'\n  AND token = 'link'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "LINK 1w APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '7 days' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '7 days'\n  AND token = 'link'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "LINK 1m APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 month' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 month'\n  AND token = 'link'\nGROUP BY venue, token"
    }
   ]
  },
  {
   "title": "LINK 1y APR",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() - interval '1 year' AS time,\n  venue || ':' || token AS text,\n  AVG(rate) * 24 * 365 * 100 AS rate\nFROM lending_rates\nWHERE\n  time >= NOW() - interval '1 year'\n  AND token = 'link'\nGROUP BY venue, token"
    }
   ]
  }
 ]
}